const languages = [
  { code: "ZA", label: "Afrikkans (South Africa)", language: "Afrikkans" },
  { code: "AL", label: "Albanian (Albania)", language: "Albanian" },
  { code: "ET", label: "Amharic (Ethiopia)", language: "Amharic" },
  { code: "DZ", label: "Arabic (Algeria)", language: "Arabic" },
  { code: "BH", label: "Arabic (Bahrain)", language: "Arabic" },
  { code: "EG", label: "Arabic (Egypt)", language: "Arabic" },
  { code: "IQ", label: "Arabic (Iraq)", language: "Arabic" },
  { code: "JO", label: "Arabic (Jordan)", language: "Arabic" },
  { code: "KW", label: "Arabic (Kuwait)", language: "Arabic" },
  { code: "LB", label: "Arabic (Lebanon)", language: "Arabic" },
  { code: "LY", label: "Arabic (Libya)", language: "Arabic" },
  { code: "MA", label: "Arabic (Morocco)", language: "Arabic" },
  { code: "OM", label: "Arabic (Oman)", language: "Arabic" },
  { code: "QA", label: "Arabic (Qatar)", language: "Arabic" },
  { code: "SA", label: "Arabic (Saudi Arabia)", language: "Arabic" },
  { code: "SY", label: "Arabic (Syria)", language: "Arabic" },
  { code: "TN", label: "Arabic (Tunisia)", language: "Arabic" },
  { code: "AE", label: "Arabic (United Arab Emirates)", language: "Arabic" },
  { code: "YE", label: "Arabic (Yemen)", language: "Arabic" },
  { code: "AM", label: "Armenian (Armenia)", language: "Armenian" },
  {
    code: "AZ",
    label: "Azerbaijani (Latin, Azerbaijan)",
    language: "Azerbaijani",
  },
  { code: "BD", label: "Bangla (Bangladesh)", language: "Bangla" },
  { code: "ES", label: "Basque", language: "Basque" },
  { code: "IN", label: "Bengali (India)", language: "Bengali" },
  {
    code: "BA",
    label: "Bosnian (Bosnia and Herzegovina)",
    language: "Bosnian",
  },
  { code: "BG", label: "Bulgarian (Bulgaria)", language: "Bulgarian" },
  { code: "MM", label: "Burmese (Myanmar)", language: "Burmese" },
  { code: "ES", label: "Catalan (Spain)", language: "Catalan" },
  {
    code: "HK",
    label: "Chinese (Cantonese, Traditional)",
    language: "Chinese",
  },
  {
    code: "CN",
    label: "Chinese (Jilu Mandarin, Simplified)",
    language: "Chinese",
  },
  {
    code: "CN",
    label: "Chinese (Mandarin, Simplified)",
    language: "Chinese",
  },
  {
    code: "CN",
    label: "Chinese (Northeastern Mandarin, Simplified)",
    language: "Chinese",
  },
  {
    code: "CN",
    label: "Chinese (Southwestern Mandarin, Simplified)",
    language: "Chinese",
  },
  {
    code: "TW",
    label: "Taiwanese Chinese (Mandarin, Simplified)",
    language: "Taiwanese Chinese",
  },
  {
    code: "CN",
    label: "Chinese (Zhongyuan Mandarin Henan, Simplified)",
    language: "Chinese",
  },
  {
    code: "CN",
    label: "Chinese (Zhongyuan Mandarin Shaanxi, Simplified)",
    language: "Chinese",
  },
  { code: "HR", label: "Croatian (Croatia)", language: "Croatian" },
  { code: "CZ", label: "Czechia (Czech)", language: "Czechia" },
  { code: "DK", label: "Danish (Denmark)", language: "Danish" },
  { code: "BE", label: "Belgium", language: "Dutch" },
  { code: "NL", label: "Dutch (Netherlands)", language: "Dutch" },
  { code: "AT", label: "English (Austria)", language: "English" },
  { code: "CA", label: "English (Canada)", language: "English" },
  { code: "HK", label: "English (Hong Kong SAR)", language: "English" },
  { code: "IE", label: "English (Ireland)", language: "English" },
  { code: "IN", label: "English (India)", language: "English" },
  { code: "KE", label: "English (Kenya)", language: "English" },
  { code: "NZ", label: "English (New Zealand)", language: "English" },
  { code: "NG", label: "English (Nigeria)", language: "English" },
  { code: "PH", label: "English (Philippines)", language: "English" },
  { code: "SG", label: "English (Singapore)", language: "English" },
  { code: "ZA", label: "English (South Africa)", language: "English" },
  { code: "TZ", label: "English (Tanzania)", language: "English" },
  { code: "GB", label: "English (United Kingdom)", language: "English" },
  { code: "US", label: "English (United States)", language: "English" },
  { code: "EE", label: "Estonian (Estonia)", language: "Estonian" },
  { code: "PH", label: "Filipino (Philippines)", language: "Filipino" },
  { code: "FI", label: "Finnish (Finland)", language: "Finnish" },
  { code: "BE", label: "French (Belgium)", language: "French" },
  { code: "CA", label: "French (Canada)", language: "French" },
  { code: "FR", label: "French (France)", language: "French" },
  { code: "CH", label: "French (Switzerland)", language: "French" },
  { code: "ES", label: "Galician", language: "Galician" },
  { code: "GE", label: "Georgian (Georgia)", language: "Georgian" },
  { code: "AT", label: "German (Austria)", language: "German" },
  { code: "DE", label: "German (Germany)", language: "German" },
  { code: "CH", label: "German (Switzerland)", language: "German" },
  { code: "GR", label: "Greek (Greece)", language: "Greek" },
  { code: "IN", label: "Gujarati (India)", language: "Gujarati" },
  { code: "IL", label: "Hebrew (Israel)", language: "Hebrew" },
  { code: "IN", label: "Hindi (India)", language: "Hindi" },
  { code: "HU", label: "Hungarian (Hungary)", language: "Hungarian" },
  { code: "IS", label: "Icelandic (Iceland)", language: "Icelandic" },
  { code: "ID", label: "Indonesian (Indonesia)", language: "Indonesian" },
  { code: "IE", label: "Irish (Ireland)", language: "Irish" },
  { code: "IT", label: "Italian (Italy)", language: "Italian" },
  { code: "JP", label: "Japanese (Japan)", language: "Japanese" },
  { code: "ID", label: "Javanese (Latin, Indonesia)", language: "Javanese" },
  { code: "IN", label: "Kannada (India)", language: "Kannada" },
  { code: "KZ", label: "Kazakh (Kazakhstan)", language: "Kazakh" },
  { code: "KH", label: "Khmer (Cambodia)", language: "Khmer" },
  { code: "KR", label: "Korean (Korea)", language: "Korean" },
  { code: "LA", label: "Lao (Laos)", language: "Lao" },
  { code: "LV", label: "Latvian (Latvia)", language: "Latvian" },
  { code: "LT", label: "Lithuanian (Lithuania)", language: "Lithuanian" },
  { code: "MK", label: "Macedonian (North Macedonia)", language: "Macedonian" },
  { code: "MY", label: "Malay (Malaysia)", language: "Malay" },
  { code: "IN", label: "Malayalam (India)", language: "Malayalam" },
  { code: "MT", label: "Maltese (Malta)", language: "Maltese" },
  { code: "IN", label: "Marathi (India)", language: "Marathi" },
  { code: "MN", label: "Mongolian (Mongolia)", language: "Mongolian" },
  { code: "NP", label: "Nepali (Nepal)", language: "Nepali" },
  {
    code: "NO",
    label: "Norwegian Bokmal (Norway)",
    language: "Norwegian Bokmal",
  },
  { code: "AF", label: "Pashto (Afghanistan)", language: "Pashto" },
  { code: "IR", label: "Persian (Iran)", language: "Persian" },
  { code: "PL", label: "Polish (Poland)", language: "Polish" },
  { code: "PT", label: "Portuguese (Portugal)", language: "Portuguese" },
  { code: "BR", label: "Portuguese (Brazil)", language: "Portuguese" },
  { code: "RO", label: "Romanian (Romania)", language: "Romanian" },
  { code: "RU", label: "Russian (Russia)", language: "Russian" },
  { code: "RS", label: "Serbian (Cyrillic Serbia)", language: "Serbian" },
  { code: "LK", label: "Sinhala (Sri Lanka)", language: "Sinhala" },
  { code: "SK", label: "Slovak (Slovakia)", language: "Slovak" },
  { code: "SI", label: "Slovenian (Slovenia)", language: "Slovenian" },
  { code: "SO", label: "Somali (Somalia)", language: "Somali" },
  { code: "AR", label: "Spanish (Argentina)", language: "Spanish" },
  { code: "BO", label: "Spanish (Bolivia)", language: "Spanish" },
  { code: "CL", label: "Spanish (Chile)", language: "Spanish" },
  { code: "CO", label: "Spanish (Colombia)", language: "Spanish" },
  { code: "CR", label: "Spanish (Costa Rica)", language: "Spanish" },
  { code: "CU", label: "Spanish (Cuba)", language: "Spanish" },
  { code: "DO", label: "Spanish (Dominican Republic)", language: "Spanish" },
  { code: "EC", label: "Spanish (Ecuador)", language: "Spanish" },
  { code: "SV", label: "Spanish (El Salvador)", language: "Spanish" },
  { code: "GN", label: "Spanish (Equartorial Guinea)", language: "Spanish" },
  { code: "GT", label: "Spanish (Guatemala)", language: "Spanish" },
  { code: "HN", label: "Spanish (Honduras)", language: "Spanish" },
  { code: "MX", label: "Spanish (Mexico)", language: "Spanish" },
  { code: "NI", label: "Spanish (Nicaragua)", language: "Spanish" },
  { code: "PA", label: "Spanish (Panama)", language: "Spanish" },
  { code: "PY", label: "Spanish (Paraguay)", language: "Spanish" },
  { code: "PE", label: "Spanish (Peru)", language: "Spanish" },
  { code: "PR", label: "Spanish (Puerto Rico)", language: "Spanish" },
  { code: "ES", label: "Spanish (Spain)", language: "Spanish" },
  { code: "US", label: "Spanish (United States)", language: "Spanish" },
  { code: "UY", label: "Spanish (Uruguay)", language: "Spanish" },
  { code: "VE", label: "Spanish (Venezuela)", language: "Spanish" },
  { code: "ID", label: "Sudanese (Indonesia)", language: "Sudanese" },
  { code: "TZ", label: "Swahili (Tanzania)", language: "Swahili" },
  { code: "SE", label: "Swedish (Sweden)", language: "Swedish" },
  { code: "IN", label: "Tamil (India)", language: "Tamil" },
  { code: "MY", label: "Tamil (Malaysia)", language: "Tamil" },
  { code: "SG", label: "Tamil (Singapore)", language: "Tamil" },
  { code: "LK", label: "Tamil (Sri Lanka)", language: "Tamil" },
  { code: "IN", label: "Telugu (India)", language: "Telugu" },
  { code: "TH", label: "Thai (Thailand)", language: "Thai" },
  { code: "TR", label: "Turkish (Turkey)", language: "Turkish" },
  { code: "UA", label: "Ukrainian (Ukraine)", language: "Ukrainian" },
  { code: "IN", label: "Urdu (India)", language: "Urdu" },
  { code: "PK", label: "Urdu (Pakistan)", language: "Urdu" },
  { code: "UZ", label: "Uzbek (Latin, Uzbekistan)", language: "Uzbek" },
  { code: "VN", label: "Vietnamese (Vietnam)", language: "Vietnamese" },
  { code: "GB", label: "Welsh (United Kingdom)", language: "Welsh" },
  { code: "ZA", label: "Zulu (South Africa)", language: "Zulu" },
];

export { languages };
